[project]
name = "tree-problem-set"
version = "0.1.0"
description = "gfg tree problems for coding interviews!"
readme = "README.md"
authors = [
    { name = "Anirudh Konidala", email = "anirudhkonidala@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
